name =input("what is your name?")
print("hello "+name)
age =input("what is your age?")
print("so your age is "+age)
ambition =input("what is the ambition of "+name +"?")
print("oh! anas wants to become a "+ambition)
name =input("what is your brother name?")
print("so his name is "+name)
age =input("what is the age of "+name+"?")
print("so his age is "+age)
enter =input("do you want to exit?press enter")
print("good"+enter)
